# Generated by Django 5.0.4 on 2025-07-01 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('customers', '0006_alter_creditcounselor_usuario'),
        ('financings', '0012_credit_fecha_actualizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoNotificacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('document', models.FileField(upload_to='documents/boleta/cliente', verbose_name='Documento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocumentoNotificacionCliente', to='customers.customer', verbose_name='Para')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocumentoNotificacionCliente', to='financings.paymentplan', verbose_name='Cuota')),
            ],
            options={
                'verbose_name': 'Documento de Boleta de Cliente',
                'verbose_name_plural': 'Documentos de Boletas de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationCustomer', to='customers.customer', verbose_name='Para')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NotificationCustomer', to='financings.paymentplan', verbose_name='Cuota')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NotificationCustomer', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Notificacion para Cliente',
                'verbose_name_plural': 'Notificaciones de Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
