# Generated by Django 5.0.4 on 2025-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_documentonotificacioncliente_notificationcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='especificaciones',
            field=models.JSONField(blank=True, null=True, verbose_name='Especificaciones'),
        ),
        migrations.AlterField(
            model_name='documentonotificacioncliente',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
