# Generated by Django 5.0.4 on 2025-07-28 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_logcategory_loglevel_systemlog_userlog'),
        ('customers', '0010_customer_valoracion'),
        ('financings', '0014_credit_valoracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(blank=True, null=True, verbose_name='Puntuacion')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario para el cliente')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente Votado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Votando')),
            ],
            options={
                'verbose_name': 'Votacion Para Clientes',
                'verbose_name_plural': 'Votaciones Para Clientes',
            },
        ),
        migrations.CreateModel(
            name='VotacionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(blank=True, null=True, verbose_name='Puntuacion')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario para el Credito')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.credit', verbose_name='Credito Votado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Votando')),
            ],
            options={
                'verbose_name': 'Votacion Para Credito',
                'verbose_name_plural': 'Votaciones Para Credito',
            },
        ),
    ]
