# Generated by Django 5.0.4 on 2025-07-28 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_votacioncliente_votacioncredito'),
        ('customers', '0011_cobranza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(default='Reporte INVERSIONES INTEGRALES EL TELAR', max_length=100, verbose_name='Nombre del Reporte')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del Informe')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Estado del Informe')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador de Informe')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
            },
        ),
        migrations.CreateModel(
            name='DetalleInformeCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.cobranza', verbose_name='Cobranza')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.informe', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Detalle de Informe',
            },
        ),
    ]
