# Generated by Django 5.0.4 on 2025-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_informe_detalleinformecobranza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
