# Generated by Django 5.0.4 on 2025-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_alter_informe_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentonotificacioncliente',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Numero de Referencia'),
        ),
    ]
