# Generated by Django 5.0.4 on 2025-08-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_documentonotificacioncliente_numero_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentonotificacioncliente',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero de Referencia'),
        ),
    ]
