# Generated by Django 5.0.4 on 2025-08-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_alter_documentonotificacioncliente_numero_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentonotificacioncliente',
            name='numero_referencia',
            field=models.CharField(blank=True, default='3696008759', max_length=255, null=True, verbose_name='Numero de Referencia'),
        ),
    ]
