# Generated by Django 5.0.4 on 2025-08-19 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_alter_documentonotificacioncliente_numero_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentonotificacioncliente',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha en que se actualizo el credito'),
        ),
    ]
