# Generated by Django 5.0.4 on 2025-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_documentonotificacioncliente_fecha_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('count', models.IntegerField(default=0, verbose_name='Contador')),
                ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
        ),
    ]
