# Generated by Django 5.0.4 on 2025-09-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_checkpoint'),
        ('financings', '0016_invoice_correo_receptor_invoice_nit_receptor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInformePagosClientesAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.recibo', verbose_name='Pago Realizado')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.informe', verbose_name='Informe')),
            ],
        ),
        migrations.CreateModel(
            name='ModelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación')], max_length=10)),
                ('data', models.JSONField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='actividades_content_e2dd74_idx')],
            },
        ),
    ]
