# Generated by Django 5.0.4 on 2025-10-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_detalleinformepagosclientesasesor_modelhistory'),
        ('subsidiaries', '0002_subsidiary_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentonotificacioncliente',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
    ]
