# Generated by Django 5.0.4 on 2025-10-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_documentonotificacioncliente_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDiarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(default='Reporte INVERSIONES INTEGRALES EL TELAR DIARIO', max_length=100, verbose_name='Nombre del Reporte')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del Informe')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Estado del Informe')),
            ],
            options={
                'verbose_name': 'Informe Diario',
                'verbose_name_plural': 'Informes Diario',
            },
        ),
        migrations.CreateModel(
            name='DetalleInformeDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.informediariosistema', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Detalle de Informe Diario',
                'verbose_name_plural': 'Detalles de Informes Diarios',
            },
        ),
    ]
