# Generated by Django 5.0.4 on 2025-10-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_informediariosistema_detalleinformediario'),
        ('subsidiaries', '0003_subsidiary_codigo_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='informediariosistema',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
    ]
