# Generated by Django 5.0.4 on 2025-10-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_informediariosistema_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinformediario',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='detalleinformediario',
            name='tipo_datos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
