# Generated by Django 5.0.4 on 2026-10-05 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0018_detalleinformediario_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='actividades_user_id_78c675_idx'),
        ),
    ]
