# Generated by Django 5.0.4 on 2025-04-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sucursal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de la Sucursal')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Sucursal')),
                ('fecha_apertura', models.DateField(verbose_name='Fecha de Apertura')),
                ('numero_telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Telfono de la Sucursal')),
                ('otro_numero_telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro Numero de Telfono de la Sucursal')),
                ('activa', models.BooleanField(default=True, verbose_name='Status de la Actividad de la Sucursal')),
                ('codigo_postal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Postal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='HorarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_apertura', models.TimeField(verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de Cierre')),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='subsidiaries.subsidiary')),
            ],
            options={
                'verbose_name': 'Horario Sucursal',
                'verbose_name_plural': 'Horarios Sucursales',
                'unique_together': {('sucursal', 'dia')},
            },
        ),
    ]
