# Generated by Django 5.0.4 on 2025-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
