# Generated by Django 5.0.4 on 2025-10-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0002_subsidiary_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='codigo_establecimiento',
            field=models.CharField(blank=True, default='1', null=True, verbose_name='CODIGO DE ESTABLECIMIENTO'),
        ),
    ]
