# Generated by Django 5.0.4 on 2025-11-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0003_subsidiary_codigo_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='numero_de_cuenta_banco',
            field=models.CharField(default='0000125', max_length=150, verbose_name='Numero de Cuenta de Banco'),
            preserve_default=False,
        ),
    ]
