# Generated by Django 5.0.4 on 2025-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0004_subsidiary_numero_de_cuenta_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='nombre_banco',
            field=models.CharField(default='Banco de Desarrollo Rural', max_length=150, verbose_name='Nombre de la Cuenta de Banco'),
        ),
    ]
