# Generated by Django 5.0.4 on 2025-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acreedor', models.CharField(max_length=100, verbose_name='Codigo de Acreedor')),
                ('nombre_acreedor', models.CharField(max_length=150, verbose_name='Nombre del Acreedor')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('tasa', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tasa')),
                ('plazo', models.IntegerField(verbose_name='Plazo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('numero_referencia', models.CharField(max_length=255, unique=True, verbose_name='Numero de Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('boleta', models.FileField(blank=True, null=True, upload_to='pagos/boletas/acreedor/', verbose_name='Boleta')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Pendiente')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Actual')),
                ('is_paid_off', models.BooleanField(default=False)),
                ('estado_aportacion', models.BooleanField(default=False)),
                ('estados_fechas', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_doc_fiscal', models.DateField(blank=True, null=True, verbose_name='Fecha De Documento Fiscal')),
                ('numero_doc', models.CharField(blank=True, max_length=155, null=True, verbose_name='Numero De Documento Fiscal')),
                ('nit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero De Documento Fiscal')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('monto_doc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto del Documento')),
                ('codigo_egreso', models.CharField(max_length=100, verbose_name='Codigo de Egreso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('numero_referencia', models.CharField(max_length=255, unique=True, verbose_name='Numero de Referencia')),
                ('boleta', models.FileField(blank=True, null=True, upload_to='pagos/boletas/gasto/', verbose_name='Boleta')),
                ('documento', models.FileField(blank=True, null=True, upload_to='pagos/boletas/gasto/documento/', verbose_name='Boleta')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('codigo_ingreso', models.CharField(max_length=100, verbose_name='Codigo de Ingreso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('numero_referencia', models.CharField(max_length=255, unique=True, verbose_name='Numero de Referencia')),
                ('boleta', models.FileField(blank=True, null=True, upload_to='pagos/boletas/otros_ingresos/', verbose_name='Boleta')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguro', models.CharField(max_length=100, verbose_name='Codigo de Seguro')),
                ('nombre_acreedor', models.CharField(max_length=150, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('tasa', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tasa')),
                ('plazo', models.IntegerField(verbose_name='Plazo')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('numero_referencia', models.CharField(max_length=255, unique=True, verbose_name='Numero de Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('boleta', models.FileField(blank=True, null=True, upload_to='pagos/boletas/acreedor/', verbose_name='Boleta')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Pendiente')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Actual')),
                ('is_paid_off', models.BooleanField(default=False)),
                ('estado_aportacion', models.BooleanField(default=False)),
                ('estados_fechas', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
