# Generated by Django 5.0.4 on 2025-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditor',
            options={'verbose_name': 'Acreedor', 'verbose_name_plural': 'Acreedores'},
        ),
        migrations.AlterModelOptions(
            name='egress',
            options={'verbose_name': 'Egreso', 'verbose_name_plural': 'Egresos'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Seguro', 'verbose_name_plural': 'Seguros'},
        ),
        migrations.AddField(
            model_name='creditor',
            name='forma_de_pago',
            field=models.CharField(default='AMORTIZACIONES A CAPITAL', max_length=75, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='forma_de_pago',
            field=models.CharField(default='AMORTIZACIONES A CAPITAL', max_length=75, verbose_name='Forma de Pago'),
        ),
    ]
