# Generated by Django 5.0.4 on 2025-01-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0002_alter_creditor_options_alter_egress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egress',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='pagos/boletas/gasto/documento/', verbose_name='Documento'),
        ),
    ]
