# Generated by Django 5.0.4 on 2025-01-21 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0003_alter_egress_documento'),
        ('financings', '0005_accountstatement_acreedor_accountstatement_seguro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financings.credit'),
        ),
    ]
