# Generated by Django 5.0.4 on 2025-02-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0004_insurance_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='egress',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Colaborador'),
        ),
        migrations.AddField(
            model_name='egress',
            name='pago_correspondiente',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pago Correspondiente'),
        ),
        migrations.AddField(
            model_name='egress',
            name='tipo_impuesto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Impuesto'),
        ),
    ]
