# Generated by Django 5.0.4 on 2025-02-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0005_egress_nombre_egress_pago_correspondiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egress',
            name='acreedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egress', to='accountings.creditor'),
        ),
        migrations.AddField(
            model_name='egress',
            name='seguro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egress', to='accountings.insurance'),
        ),
    ]
