# Generated by Django 5.0.4 on 2025-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0007_egress_tipo_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egress',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='egress',
            name='monto_doc',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Monto del Documento'),
        ),
    ]
