# Generated by Django 5.0.4 on 2025-02-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0008_alter_egress_monto_alter_egress_monto_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero de Referencia'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=255, verbose_name='Numero de Referencia'),
        ),
    ]
