# Generated by Django 5.0.4 on 2025-03-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0009_alter_creditor_numero_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='estado_aportacion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='estado_aportacion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
