# Generated by Django 5.0.4 on 2025-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0010_alter_creditor_estado_aportacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='egress',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='income',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
    ]
