# Generated by Django 5.0.4 on 2025-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0011_creditor_creation_date_egress_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='excedente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Monto de excedente'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='excedente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Monto de excedente'),
        ),
    ]
