# Generated by Django 5.0.4 on 2025-11-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0013_creditor_sucursal_egress_sucursal_income_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cancelacion'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cancelacion'),
        ),
    ]
