# Generated by Django 5.0.4 on 2025-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0014_creditor_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='fecha_entrar_en_mora',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha en entrar en Mora'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='fecha_entrar_en_mora',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha en entrar en Mora'),
        ),
    ]
