# Generated by Django 5.0.4 on 2025-01-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_product_or_service', models.CharField(choices=[('AGROPECUARIO Y/O PRODUCTIVO', 'AGROPECUARIO Y/O PRODUCTIVO'), ('COMERCIO', 'COMERCIO'), ('SERVICIOS', 'SERVICIOS'), ('CONSUMO', 'CONSUMO'), ('VIVIENDA', 'VIVIENDA')], max_length=75, verbose_name='Tipo de Producto o Servicio')),
                ('total_value_of_the_product_or_service', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total del Producto o Servicio')),
                ('investment_plan_description', models.TextField(blank=True, null=True, verbose_name='Descripción del Plan de Inversión')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Inicial')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Mensual')),
                ('transfers_or_transfer_of_funds', models.BooleanField(verbose_name='Transferencias o Traslado de Fondos')),
                ('type_of_transfers_or_transfer_of_funds', models.CharField(choices=[('Local', 'Local'), ('Internacional', 'Internacional')], max_length=75, verbose_name='Tipo de Transferencia')),
                ('investment_plan_code', models.CharField(max_length=25, unique=True, verbose_name='Código de Plan de Inversion')),
            ],
            options={
                'verbose_name': 'Plan de Inversión',
                'verbose_name_plural': 'Planes de Inversión',
            },
        ),
    ]
