# Generated by Django 5.0.4 on 2025-11-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0002_initial'),
        ('subsidiaries', '0004_subsidiary_numero_de_cuenta_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='forma_de_pago',
            field=models.CharField(choices=[('NIVELADA', 'NIVELADA'), ('AMORTIZACIONES A CAPITAL', 'AMORTIZACIONES A CAPITAL')], default='NIVELADA', max_length=75, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='plazo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Tasa de Interes'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Inicial'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Mensual'),
        ),
    ]
