# Generated by Django 5.0.4 on 2025-11-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0003_investmentplan_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='transfers_or_transfer_of_funds',
            field=models.BooleanField(blank=True, null=True, verbose_name='Transferencias o Traslado de Fondos'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='type_of_transfers_or_transfer_of_funds',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Internacional', 'Internacional')], max_length=75, null=True, verbose_name='Tipo de Transferencia'),
        ),
    ]
