# Generated by Django 5.0.4 on 2025-11-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0004_alter_investmentplan_transfers_or_transfer_of_funds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Tasa de Interes'),
        ),
    ]
