# Generated by Django 5.0.4 on 2025-12-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0005_alter_investmentplan_tasa_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='credito_anterior_vigente',
            field=models.JSONField(blank=True, null=True, verbose_name='Credito Anterior Vigente'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='fiador',
            field=models.JSONField(blank=True, null=True, verbose_name='Fiador'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='tipo_pagare',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de pagare'),
        ),
    ]
