# Generated by Django 5.0.4 on 2026-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0007_investmentplan_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='fecha_finalizacion_gracia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion de Gracia'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='plazo_gracia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo de Gracia'),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='forma_de_pago',
            field=models.CharField(choices=[('NIVELADA', 'NIVELADA'), ('AMORTIZACIONES A CAPITAL', 'AMORTIZACIONES A CAPITAL'), ('INTERES MENSUAL Y CAPITAL AL VENCIMIENTO', 'INTERES MENSUAL Y CAPITAL AL VENCIMIENTO'), ('INTERES Y CAPITAL AL VENCIMIENTO', 'INTERES Y CAPITAL AL VENCIMIENTO')], default='NIVELADA', max_length=75, verbose_name='Forma de Pago'),
        ),
    ]
