# Generated by Django 5.0.4 on 2026-07-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0008_investmentplan_fecha_finalizacion_gracia_and_more'),
        ('customers', '0021_immigrationstatus_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='asesor_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.creditcounselor'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='estado_aprobacion',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Estado de Aprobacion'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='garantias',
            field=models.JSONField(blank=True, null=True, verbose_name='Garantias de la Solicitud de Credito'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Tipo de documento'),
        ),
    ]
