# Generated by Django 5.0.4 on 2026-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0009_investmentplan_asesor_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='tipo_documento',
            field=models.CharField(blank=True, default='PAGARE', max_length=75, null=True, verbose_name='Tipo de documento'),
        ),
    ]
