# Generated by Django 5.0.4 on 2026-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0010_alter_investmentplan_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='notarios',
            field=models.JSONField(blank=True, null=True, verbose_name='Notarios'),
        ),
    ]
