# Generated by Django 5.0.4 on 2026-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0011_investmentplan_notarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='diganostico_oportunidad',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico de Oportunidades'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='evaluacion_mercado',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluación del Mercado'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='mitigadores',
            field=models.TextField(blank=True, null=True, verbose_name='Mitigadores'),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='riesgo_comercial',
            field=models.TextField(blank=True, null=True, verbose_name='Riesgo Comercial'),
        ),
    ]
