# Generated by Django 5.0.4 on 2026-07-27 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0012_investmentplan_diganostico_oportunidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedientePlanNotario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('investment_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InvestmentPlan.investmentplan')),
                ('notario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente Plan Notario',
                'verbose_name_plural': 'Expedientes Plan Notarios',
            },
        ),
    ]
