# Generated by Django 5.0.4 on 2026-07-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0014_alter_expedienteplannotario_notario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedienteplannotario',
            name='investment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestmentPlan.investmentplan'),
        ),
    ]
