# Generated by Django 5.0.4 on 2026-09-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0015_alter_expedienteplannotario_investment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedienteplannotario',
            name='asunto_expediente',
            field=models.TextField(blank=True, null=True, verbose_name='Asunto del Expediente'),
        ),
    ]
