# Generated by Django 5.0.4 on 2025-01-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'Codigo',
                'verbose_name_plural': 'Codigos',
            },
        ),
    ]
