# Generated by Django 5.0.4 on 2024-10-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Codigo', 'verbose_name_plural': 'Codigos'},
        ),
    ]
