# Generated by Django 5.0.4 on 2025-07-01 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_initial'),
        ('customers', '0006_alter_creditcounselor_usuario'),
        ('financings', '0012_credit_fecha_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('cuota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financings.paymentplan')),
            ],
        ),
    ]
