# Generated by Django 5.0.4 on 2025-08-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_tokencliente'),
        ('customers', '0013_cobranza_fecha_limite_cuota'),
        ('financings', '0015_alter_credit_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='tokencliente',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financings.paymentplan'),
        ),
    ]
