# Generated by Django 5.0.4 on 2025-01-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSourcesOfIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_income', models.CharField(max_length=100, verbose_name='Fuente de Ingreso')),
                ('nit', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
            ],
            options={
                'verbose_name': 'Otra Fuente de Ingreso',
                'verbose_name_plural': 'Otras Fuentes de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('reference_type', models.CharField(choices=[('Personales', 'Personales'), ('Laborales', 'Laborales'), ('Comerciales', 'Comerciales'), ('Bancarias', 'Bancarias')], max_length=100, verbose_name='Tipo de Referencia')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='WorkingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150, verbose_name='Puesto')),
                ('company_name', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('working_hours', models.CharField(max_length=70, verbose_name='Horario de Trabajo')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('source_of_income', models.CharField(choices=[('Relación de Dependencia', 'Relación de Dependencia'), ('Negocio Propio', 'Negocio Propio'), ('Otra', 'Otra')], max_length=90, verbose_name='Fuente de Ingreso')),
                ('income_detail', models.TextField(blank=True, null=True, verbose_name='Detalle de Ingreso')),
                ('employment_status', models.CharField(choices=[('Empleado a Tiempo Completo', 'Empleado a Tiempo Completo'), ('Empleado a Tiempo Parcial', 'Empleado a Tiempo Parcial'), ('Autónomo', 'Autónomo'), ('Desempleado', 'Desempleado'), ('Trabajador Temporal', 'Trabajador Temporal'), ('Contratista', 'Contratista'), ('Freelancer', 'Freelancer'), ('Estudiante', 'Estudiante'), ('Jubilado', 'Jubilado'), ('Hogar', 'Hogar'), ('Practicante o Pasante', 'Practicante o Pasante'), ('Trabajador a Domicilio', 'Trabajador a Domicilio'), ('Voluntario', 'Voluntario')], max_length=150, verbose_name='Estado Laboral')),
            ],
            options={
                'verbose_name': 'Información Laboral',
                'verbose_name_plural': 'Informaciones Laborales',
            },
        ),
    ]
