# Generated by Django 5.0.4 on 2024-05-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSourcesOfIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_income', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('reference_type', models.CharField(choices=[('Personales', 'Personales'), ('Laborales', 'Laborales'), ('Comerciales', 'Comerciales'), ('Bancarias', 'Bancarias')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.CharField(max_length=70)),
                ('working_hours', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=20)),
                ('source_of_income', models.CharField(choices=[('Relación de Dependencia', 'Relación de Dependencia'), ('Negocio Propio', 'Negocio Propio'), ('Otra', 'Otra')], max_length=90)),
                ('income_detail', models.TextField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('Empleado a Tiempo Completo', 'Empleado a Tiempo Completo'), ('Empleado a Tiempo Parcial', 'Empleado a Tiempo Parcial'), ('Autónomo', 'Autónomo'), ('Desempleado', 'Desempleado'), ('Trabajador Temporal', 'Trabajador Temporal'), ('Contratista', 'Contratista'), ('Freelancer', 'Freelancer'), ('Estudiante', 'Estudiante'), ('Jubilado', 'Jubilado'), ('Hogar', 'Hogar'), ('Practicante o Pasante', 'Practicante o Pasante'), ('Trabajador a Domicilio', 'Trabajador a Domicilio'), ('Voluntario', 'Voluntario')], max_length=150)),
            ],
        ),
    ]
