# Generated by Django 5.0.4 on 2026-06-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialInformation', '0003_othersourcesofincome_creation_date_and_more'),
        ('customers', '0021_immigrationstatus_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Tipo de Gasto')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='GastoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('frecuencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Frecuencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('tipo_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinancialInformation.tipogasto')),
            ],
        ),
    ]
