# Generated by Django 5.0.4 on 2024-05-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=90)),
                ('number', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('postal_code', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=90)),
                ('type_address', models.CharField(choices=[('Dirección de Casa', 'Dirección de Casa'), ('Dirección de Trabajo', 'Dirección de Trabajo'), ('Dirección Personal', 'Dirección Personal')], max_length=90)),
            ],
        ),
    ]
