# Generated by Django 5.0.4 on 2025-01-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, verbose_name='Dirección particular o sede social completa')),
                ('number', models.CharField(max_length=90, verbose_name='Zona')),
                ('city', models.CharField(max_length=100, verbose_name='Departamento')),
                ('state', models.CharField(max_length=90, verbose_name='Municipio')),
                ('country', models.CharField(default='GUATEMALA', max_length=90, verbose_name='País')),
                ('type_address', models.CharField(choices=[('Dirección de Casa', 'Dirección de Casa'), ('Dirección de Trabajo', 'Dirección de Trabajo'), ('Dirección Personal', 'Dirección Personal')], max_length=90, verbose_name='Tipo de Dirección')),
                ('latitud', models.CharField(max_length=120, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=120, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Municiopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
