<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-23 21:59
=======
# Generated by Django 5.0.4 on 2024-12-26 21:25
>>>>>>> bd470ff (migraciones)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='municiopio',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.departamento'),
        ),
    ]
