# Generated by Django 5.0.4 on 2024-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitud',
            field=models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitud',
            field=models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Longitud'),
        ),
    ]
