# Generated by Django 5.0.4 on 2025-04-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_initial'),
        ('customers', '0004_occupation_profession_customer_level_of_education_and_more'),
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='address',
            name='subsidiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subsidiaries.subsidiary'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='municiopio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type_address',
            field=models.CharField(choices=[('Dirección de Casa', 'Dirección de Casa'), ('Dirección de Trabajo', 'Dirección de Trabajo'), ('Dirección Personal', 'Dirección Personal'), ('Dirección de Sucursal', 'Dirección de Sucursal')], max_length=90, verbose_name='Tipo de Dirección'),
        ),
    ]
