# Generated by Django 5.0.4 on 2024-10-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_latitud_alter_address_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=120, verbose_name='Dirección particular o sede social completa'),
        ),
    ]
