# Generated by Django 5.0.4 on 2024-11-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_departamento_municiopio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municiopio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='municiopio',
            name='nombre',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nombre del Municipio'),
        ),
    ]
