# Generated by Django 5.0.4 on 2025-07-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_codigo_postal_address_subsidiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type_address',
            field=models.CharField(blank=True, choices=[('Dirección de Casa', 'Dirección de Casa'), ('Dirección de Trabajo', 'Dirección de Trabajo'), ('Dirección Personal', 'Dirección Personal'), ('Dirección de Sucursal', 'Dirección de Sucursal')], max_length=90, null=True, verbose_name='Tipo de Dirección'),
        ),
    ]
