# Generated by Django 5.0.4 on 2024-05-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.address')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.imagen')),
            ],
        ),
    ]
