# Generated by Django 5.0.4 on 2025-04-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenSubsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/sucursal/', verbose_name='Imagen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiaries.subsidiary')),
            ],
            options={
                'verbose_name': 'Imagen de la Sucursal',
                'verbose_name_plural': 'Imágenes de las Sucursales',
            },
        ),
    ]
