# Generated by Django 5.0.4 on 2024-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Administrador', 'Administrador'), ('Contabilidad', 'Contabilidad'), ('Secretaria', 'Secretaria'), ('Programador', 'Programador')], max_length=75)),
                ('description', models.TextField()),
            ],
        ),
    ]
