# Generated by Django 5.0.4 on 2025-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Permiso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion acerca del permiso')),
                ('codigo_permiso', models.CharField(max_length=75, unique=True, verbose_name='Codigo del Permiso')),
                ('estado', models.BooleanField(verbose_name='Estado del Permiso')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
