# Generated by Django 5.0.4 on 2025-06-24 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_permiso_remove_role_permissions_delete_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Permiso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion acerca del permiso')),
                ('estado', models.BooleanField(verbose_name='Estado del Permiso')),
            ],
            options={
                'verbose_name': 'Categoria de Permiso',
                'verbose_name_plural': 'Categorias de Permisos',
            },
        ),
        migrations.AddField(
            model_name='permiso',
            name='categoria_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.categoriapermiso'),
        ),
    ]
