# Generated by Django 5.0.4 on 2025-06-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_categoriapermiso_permiso_categoria_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapermiso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion acerca de la Categoria (Modulo)'),
        ),
        migrations.AlterField(
            model_name='categoriapermiso',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado de la Categoria del Permiso'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado del Permiso'),
        ),
    ]
