# Generated by Django 5.0.4 on 2025-06-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_categoriapermiso_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado del Rol'),
        ),
    ]
