# Generated by Django 5.0.4 on 2025-06-23 17:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_permiso_remove_role_permissions_delete_userrole'),
        ('subsidiaries', '0002_subsidiary_descripcion'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha en que se actualizo el usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='nit',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Numero de NIT'),
        ),
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.role'),
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.permiso', verbose_name='Permiso de Usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
            },
        ),
    ]
