# Generated by Django 5.0.4 on 2024-07-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Administradora', 'Administradora'), ('Programador', 'Programador'), ('Programadora', 'Programadora'), ('Secretaria', 'Secretaria'), ('Secretario', 'Secretario'), ('Contador', 'Contador'), ('Contadora', 'Contadora')], default='Administrador', max_length=50, verbose_name='Rol de Usuario'),
        ),
    ]
