# Generated by Django 5.0.4 on 2025-06-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_rol_old_alter_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol_old',
        ),
    ]
