# Generated by Django 5.0.4 on 2025-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_rol_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Identificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Usuario'),
        ),
    ]
