# Generated by Django 5.0.4 on 2025-01-09 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=25, unique=True, verbose_name='Código de Cliente')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('type_identification', models.CharField(choices=[('DPI', 'DPI'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DPI', max_length=50, verbose_name='Tipo de Identificación')),
                ('identification_number', models.CharField(max_length=15, unique=True, verbose_name='Número de Identificación')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('status', models.CharField(choices=[('Revisión de documentos', 'Revisión de documentos'), ('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado'), ('Posible Cliente', 'Posible Cliente'), ('Dar de Baja', 'Dar de Baja')], default='Posible Cliente', max_length=75, verbose_name='Estado')),
                ('date_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('number_nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('place_birth', models.CharField(max_length=75, verbose_name='Lugar de Nacimiento')),
                ('marital_status', models.CharField(max_length=50, verbose_name='Estado Civil')),
                ('profession_trade', models.CharField(max_length=75, verbose_name='Profesión u Oficio')),
                ('gender', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', max_length=50, verbose_name='Género')),
                ('nationality', models.CharField(default='Guatemala', max_length=75, verbose_name='Nacionalidad')),
                ('person_type', models.CharField(choices=[('Individual (PI)', 'Individual (PI)'), ('Juridica (PJ)', 'Juridica (PJ)')], max_length=50, verbose_name='Tipo de Persona')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('asesor', models.CharField(blank=True, default='PENDIENTE', max_length=100, null=True, verbose_name='Asesor del Credito')),
                ('fehca_vencimiento_de_tipo_identificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Vencimiento del Tipo de Identificacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ImmigrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Condicion Migratoria',
                'verbose_name_plural': 'Condiciones Migratorias',
            },
        ),
    ]
