# Generated by Django 5.0.4 on 2024-05-17 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=25, unique=True)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('type_identification', models.CharField(choices=[('DPI', 'DPI'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DPI', max_length=50)),
                ('identification_number', models.CharField(max_length=15, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_birth', models.DateField()),
                ('number_nit', models.CharField(max_length=20, unique=True)),
                ('place_birth', models.CharField(max_length=75)),
                ('marital_status', models.CharField(max_length=50)),
                ('profession_trade', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', max_length=50)),
                ('nationality', models.CharField(default='Guatemala', max_length=75)),
                ('person_type', models.CharField(choices=[('Indivicual (PI)', 'Indivicual (PI)'), ('Juridica (PJ)', 'Juridica (PJ)')], max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('immigration_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.immigrationstatus')),
            ],
        ),
    ]
