# Generated by Django 5.0.4 on 2024-05-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=25, unique=True)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('type_identification', models.CharField(choices=[('DPI', 'DPI'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DPI', max_length=50)),
                ('identification_number', models.CharField(max_length=15, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('Revisión de documentos', 'Revisión de documentos'), ('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado'), ('Posible Cliente', 'Posible Cliente')], default='Posible Cliente', max_length=75)),
                ('date_birth', models.DateField()),
                ('number_nit', models.CharField(max_length=20, unique=True)),
                ('place_birth', models.CharField(max_length=75)),
                ('marital_status', models.CharField(max_length=50)),
                ('profession_trade', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', max_length=50)),
                ('nationality', models.CharField(default='Guatemala', max_length=75)),
                ('person_type', models.CharField(choices=[('Indivicual (PI)', 'Indivicual (PI)'), ('Juridica (PJ)', 'Juridica (PJ)')], max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImmigrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
