# Generated by Django 5.0.4 on 2025-01-09 22:30

import apps.customers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.customers.models.set_null_user), to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='customer',
            name='immigration_status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.immigrationstatus', verbose_name='Condición Migratorio'),
        ),
    ]
