# Generated by Django 5.0.4 on 2024-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='person_type',
            field=models.CharField(choices=[('Individual (PI)', 'Individual (PI)'), ('Juridica (PJ)', 'Juridica (PJ)')], max_length=50, verbose_name='Tipo de Persona'),
        ),
    ]
