# Generated by Django 5.0.4 on 2024-10-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='asesor',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=100, null=True, verbose_name='Asesor del Credito'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fehca_vencimiento_de_tipo_identificacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Vencimiento del Tipo de Identificacion'),
        ),
    ]
