# Generated by Django 5.0.4 on 2025-04-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ocupacion', models.CharField(max_length=100, verbose_name='Codigo de Ocupación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Ocupación')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_profesion', models.CharField(max_length=100, verbose_name='Codigo de Profesion')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Profesión')),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('Ninguna', 'Ninguna'), ('Primaria', 'Primaria'), ('Basico', 'Basico'), ('Diversificado', 'Diversificado'), ('Superior', 'Superior')], default='Ninguna', max_length=100, null=True, verbose_name='Nivel de Escolaridad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='level_of_education_superior',
            field=models.CharField(blank=True, choices=[('Terciario', 'Terciario'), ('Universitario', 'Universitario'), ('Postgrado', 'Postgrado'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=100, null=True, verbose_name='Nivel de Escolaridad Superior'),
        ),
        migrations.AddField(
            model_name='customer',
            name='other_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Otro Numero de Teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profession_trade',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Profesión u Oficio'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ocupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.occupation', verbose_name='Ocupacion'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.profession', verbose_name='Profesion'),
        ),
    ]
