# Generated by Django 5.0.4 on 2025-06-25 15:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_occupation_profession_customer_level_of_education_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCounselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Asesor')),
                ('apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido del Asesor')),
                ('codigo_asesor', models.CharField(max_length=50, unique=True, verbose_name='Código de Asesor')),
                ('type_identification', models.CharField(choices=[('DPI', 'DPI'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='DPI', max_length=50, verbose_name='Tipo de Identificación')),
                ('identification_number', models.CharField(max_length=15, unique=True, verbose_name='Número de Identificación')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='asesor/profile_pics/', verbose_name='Foto de Perfil')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha en que se actualizo el usuario')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('gender', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', max_length=50, verbose_name='Género')),
                ('nit', models.CharField(blank=True, max_length=75, null=True, verbose_name='Numero de NIT')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asesor de Crédito',
                'verbose_name_plural': 'Asesores de Credito',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='new_asesor_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.creditcounselor', verbose_name='Asesor de este Credito'),
        ),
    ]
