# Generated by Django 5.0.4 on 2025-07-08 00:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_creditcounselor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='completado',
            field=models.BooleanField(default=True, verbose_name='Estado de Registro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Token Cliente'),
        ),
    ]
