# Generated by Django 5.0.4 on 2025-07-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_completado_customer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lugar_emision_tipo_identificacion_departamento',
            field=models.CharField(blank=True, default='Alta Verapaz', max_length=100, null=True, verbose_name='Lugar de Emision (Departamento)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lugar_emision_tipo_identificacion_municipio',
            field=models.CharField(blank=True, default='Cobán', max_length=100, null=True, verbose_name='Lugar de Emision (Municipio)'),
        ),
    ]
