# Generated by Django 5.0.4 on 2025-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_lugar_emision_tipo_identificacion_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Identificación'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_nit',
            field=models.CharField(max_length=50, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
