# Generated by Django 5.0.4 on 2025-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='valoracion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Puntuacion del cliente'),
        ),
    ]
