# Generated by Django 5.0.4 on 2025-07-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_valoracion'),
        ('financings', '0015_alter_credit_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cobranza', models.CharField(max_length=75)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_gestion', models.DateTimeField()),
                ('tipo_gestion', models.CharField(max_length=75)),
                ('resultado', models.CharField(max_length=75)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mora_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_promesa_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_cobranza', models.CharField(default='pendiente', max_length=75)),
                ('telefono_contacto', models.CharField(max_length=75)),
                ('asesor_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranzas_gestionadas', to='customers.creditcounselor')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranzas', to='financings.credit')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_cobranza', to='financings.paymentplan')),
            ],
            options={
                'verbose_name': 'Cobranza',
                'verbose_name_plural': 'Cobranzas',
                'ordering': ['-fecha_gestion'],
            },
        ),
    ]
