# Generated by Django 5.0.4 on 2025-07-30 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_cobranza'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcounselor',
            name='recordatorio_clientes',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha en que se recordara a los clientes'),
        ),
    ]
