# Generated by Django 5.0.4 on 2025-07-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_creditcounselor_recordatorio_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='fecha_limite_cuota',
            field=models.DateField(blank=True, null=True),
        ),
    ]
