# Generated by Django 5.0.4 on 2025-08-23 08:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_cobranza_fecha_limite_cuota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Contador'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha en que se actualizo la cobranza'),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='fecha_seguimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobranza',
            name='fecha_gestion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación')], max_length=20)),
                ('datos_anteriores', models.JSONField(default=dict)),
                ('datos_nuevos', models.JSONField(default=dict)),
                ('observaciones_cambio', models.TextField(blank=True, null=True)),
                ('cobranza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='customers.cobranza')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cobranza',
                'verbose_name_plural': 'Historial de Cobranzas',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
