# Generated by Django 5.0.4 on 2025-08-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_cobranza_count_cobranza_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='codigo_gestion',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
