# Generated by Django 5.0.4 on 2025-08-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_cobranza_codigo_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcobranza',
            name='cobranza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='customers.cobranza'),
        ),
    ]
