# Generated by Django 5.0.4 on 2025-10-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_historialcobranza_cobranza'),
        ('subsidiaries', '0002_subsidiary_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcounselor',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
    ]
