# Generated by Django 5.0.4 on 2025-10-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_creditcounselor_sucursal_customer_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='numero_identificacion_sucursal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Numero de Identificacion Sucursal por Cliente'),
        ),
    ]
