# Generated by Django 5.0.4 on 2025-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_customer_numero_identificacion_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_nit',
            field=models.CharField(default='CF', max_length=50, verbose_name='NIT'),
        ),
    ]
