# Generated by Django 5.0.4 on 2025-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customer_email_alter_customer_number_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number_nit',
            field=models.CharField(blank=True, default='CF', max_length=50, null=True, verbose_name='NIT'),
        ),
    ]
