# Generated by Django 5.0.4 on 2024-07-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InvestmentPlan', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsGuarantees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_garantia', models.CharField(choices=[('HIPOTECA', 'HIPOTECA'), ('DERECHO DE POSESION', 'DERECHO DE POSESION'), ('FIADOR', 'FIADOR'), ('CHEQUE', 'CHEQUE'), ('VEHICULO', 'VEHICULO'), ('MOBILIARIA', 'MOBILIARIA')], max_length=75, verbose_name='Tipo de Garantia')),
                ('especificaciones', models.JSONField(verbose_name='Especificaciones')),
                ('valor_cobertura', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Cobertura')),
            ],
            options={
                'verbose_name': 'Detalle de Garantia',
                'verbose_name_plural': 'Detalles de Garantias',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposito', models.TextField(verbose_name='Proposito')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('plazo', models.IntegerField(verbose_name='Plazo')),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Interes')),
                ('forma_de_pago', models.CharField(choices=[('NIVELADA', 'NIVELADA'), ('AMORTIZACIONES A CAPITAL', 'AMORTIZACIONES A CAPITAL')], default='MENSUAL', max_length=75, verbose_name='Forma de Pago')),
                ('frecuencia_pago', models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMANAL', 'SEMANAL')], default='NIVELADA', max_length=75, verbose_name='Frecuencia de Pago')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('tipo_credito', models.CharField(choices=[('AGROPECUARIO Y/O PRODUCTIVO', 'AGROPECUARIO Y/O PRODUCTIVO'), ('COMERCIO', 'COMERCIO'), ('SERVICIOS', 'SERVICIOS'), ('CONSUMO', 'CONSUMO'), ('VIVIENDA', 'VIVIENDA')], max_length=75, verbose_name='Tipo de Credito')),
                ('codigo_credito', models.CharField(max_length=25, unique=True, verbose_name='Codigo Credito')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
                ('destino_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvestmentPlan.investmentplan', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_desembolso', models.CharField(choices=[('CHEQUE', 'CHEQUE'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('CANCELACION ANTERIOR', 'CANCELACION ANTERIOR')], max_length=75, verbose_name='Forma de Desmbolso')),
                ('monto_desembolso', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('gasto_administrativo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gasto Administrativo')),
                ('monto_seguro', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto de Seguro')),
                ('credit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.credit', verbose_name='Credito')),
            ],
            options={
                'verbose_name': 'Desembolso',
                'verbose_name_plural': 'Desembolsos',
            },
        ),
        migrations.CreateModel(
            name='Guarantees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('suma_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Suma Total de Garantia')),
                ('credit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.credit', verbose_name='Credito')),
            ],
            options={
                'verbose_name': 'Garantia',
                'verbose_name_plural': 'Garantias',
            },
        ),
    ]
