# Generated by Django 5.0.4 on 2024-07-18 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsguarantees',
            name='garantia_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='financings.guarantees', verbose_name='Garantia'),
            preserve_default=False,
        ),
    ]
