# Generated by Django 5.0.4 on 2024-10-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo',
            options={'verbose_name': 'Recibo', 'verbose_name_plural': 'Recibos'},
        ),
    ]
