# Generated by Django 5.0.4 on 2025-01-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente'),
        ),
    ]
