# Generated by Django 5.0.4 on 2024-11-09 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('numero_factura', models.IntegerField(verbose_name='Numero de Factura')),
                ('recibo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.recibo', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
