# Generated by Django 5.0.4 on 2024-12-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='total_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de totales'),
        ),
    ]
