# Generated by Django 5.0.4 on 2024-09-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Limite'),
        ),
    ]
