# Generated by Django 5.0.4 on 2024-09-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Debito'),
        ),
    ]
