# Generated by Django 5.0.4 on 2024-08-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsguarantees',
            name='tipo_garantia',
            field=models.CharField(choices=[('HIPOTECA', 'HIPOTECA'), ('DERECHO DE POSESION HIPOTECA', 'DERECHO DE POSESION HIPOTECA'), ('FIADOR', 'FIADOR'), ('CHEQUE', 'CHEQUE'), ('VEHICULO', 'VEHICULO'), ('MOBILIARIA', 'MOBILIARIA')], max_length=75, verbose_name='Tipo de Garantia'),
        ),
    ]
