# Generated by Django 5.0.4 on 2024-07-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0002_initial'),
        ('financings', '0002_detailsguarantees_garantia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='destino_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvestmentPlan.investmentplan', verbose_name='Destino'),
        ),
    ]
