# Generated by Django 5.0.4 on 2024-09-27 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0002_paymentplan_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_statement', to='financings.disbursement'),
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_statement', to='financings.payment'),
        ),
    ]
