# Generated by Django 5.0.4 on 2024-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0002_alter_payment_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
