# Generated by Django 5.0.4 on 2024-08-17 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0002_alter_detailsguarantees_tipo_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='forma_de_pago',
            field=models.CharField(choices=[('NIVELADA', 'NIVELADA'), ('AMORTIZACIONES A CAPITAL', 'AMORTIZACIONES A CAPITAL')], default='NIVELADA', max_length=75, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='frecuencia_pago',
            field=models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('TRIMESTRAL', 'TRIMESTRAL'), ('SEMANAL', 'SEMANAL')], default='MENSUAL', max_length=75, verbose_name='Frecuencia de Pago'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='forma_desembolso',
            field=models.CharField(choices=[('APLICACIÓN GASTOS', 'APLICACIÓN GASTOS'), ('APLICACIÓN DE AMPLIACIÓN DE CRÉDITO VIGENTE', 'APLICACIÓN DE AMPLIACIÓN DE CRÉDITO VIGENTE'), ('CANCELACIÓN DE CRÉDITO VIGENTE', 'CANCELACIÓN DE CRÉDITO VIGENTE')], max_length=75, verbose_name='Forma de Desembolso'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('numero_referencia', models.CharField(max_length=255, verbose_name='Numero de Referencia')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emision')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado_transaccion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.credit', verbose_name='Credito')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='No.Mes')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateTimeField(verbose_name='Fecha de Vencimiento')),
                ('monto_prestado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Prestado')),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mora')),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.BooleanField(default=False)),
                ('credit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.credit')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PAGO REALIZADO', 'Pago Realizado'), ('PAGO FALLIDO', 'Pago Fallido')], max_length=50, verbose_name='Tipo de Transacción')),
                ('previous_status', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nuevo Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mora')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Intereses')),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Capital')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Restante')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Transacción')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
            },
        ),
    ]
