# Generated by Django 5.0.4 on 2025-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0002_payment_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
