# Generated by Django 5.0.4 on 2024-11-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(blank=True, default=1, null=True, verbose_name='No.Mes')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Prestado')),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mora')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Capital')),
                ('installment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cuota')),
                ('status', models.BooleanField(default=False)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Pendiente')),
                ('interes_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interes Pagado')),
                ('mora_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mora Pagada')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Limite')),
                ('cambios', models.BooleanField(default=False)),
                ('numero_referencia', models.CharField(blank=True, default='NAN', max_length=255, null=True, verbose_name='Numero de Referencia')),
                ('cuota_vencida', models.BooleanField(default=False)),
                ('credit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.credit')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
    ]
