# Generated by Django 5.0.4 on 2024-09-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0003_paymentplan_saldo_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='interes_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interes Acumulada'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='interes_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interes Pagado'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='mora_acumulada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mora Acumulada'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='mora_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mora Pagada'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Pendiente'),
        ),
    ]
