# Generated by Django 5.0.4 on 2024-09-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0003_accountstatement_disbursement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='numero_referencia',
            field=models.CharField(max_length=255, unique=True, verbose_name='Numero de Referencia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='numero_referencia',
            field=models.CharField(max_length=255, unique=True, verbose_name='Numero de Referencia'),
        ),
    ]
