# Generated by Django 5.0.4 on 2025-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0003_disbursement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsguarantees',
            name='tipo_garantia',
            field=models.CharField(choices=[('HIPOTECA', 'HIPOTECA'), ('DERECHO DE POSESION HIPOTECA', 'DERECHO DE POSESION HIPOTECA'), ('FIADOR', 'FIADOR'), ('CHEQUE / PAGARE', 'CHEQUE / PAGARE'), ('VEHICULO', 'VEHICULO'), ('MOBILIARIA', 'MOBILIARIA')], max_length=75, verbose_name='Tipo de Garantia'),
        ),
    ]
