# Generated by Django 5.0.4 on 2024-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0003_alter_credit_destino_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='codigo_credito',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Codigo Credito'),
        ),
    ]
