# Generated by Django 5.0.4 on 2024-09-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0004_alter_accountstatement_numero_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='cambios',
            field=models.BooleanField(default=False),
        ),
    ]
