# Generated by Django 5.0.4 on 2024-11-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0004_paymentplan_principal_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='capital_generado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='interes_generado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
