# Generated by Django 5.0.4 on 2025-01-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0001_initial'),
        ('financings', '0004_alter_detailsguarantees_tipo_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='acreedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_statement', to='accountings.creditor'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='seguro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_statement', to='accountings.insurance'),
        ),
        migrations.AddField(
            model_name='payment',
            name='acreedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accountings.creditor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seguro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accountings.insurance'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='acreedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='accountings.creditor'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='seguro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='accountings.insurance'),
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_statements', to='financings.credit'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tipo_pago',
            field=models.CharField(choices=[('DESEMBOLSO', 'DESEMBOLSO'), ('CREDITO', 'CREDITO'), ('GASTO', 'GASTO'), ('COMPRA', 'COMPRA'), ('SEGURO', 'SEGURO'), ('INGRESO', 'INGRESO'), ('CLIENTE', 'CLIENTE'), ('ACREEDOR', 'ACREEDOR'), ('SEGURO', 'SEGURO')], default='CREDITO', max_length=75, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='credit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financings.credit', verbose_name='Credito'),
        ),
    ]
