# Generated by Django 5.0.4 on 2025-01-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0005_accountstatement_acreedor_accountstatement_seguro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tipo_pago',
            field=models.CharField(choices=[('DESEMBOLSO', 'DESEMBOLSO'), ('CREDITO', 'CREDITO'), ('GASTO', 'GASTO'), ('COMPRA', 'COMPRA'), ('SEGURO', 'SEGURO'), ('INGRESO', 'INGRESO'), ('CLIENTE', 'CLIENTE'), ('ACREEDOR', 'ACREEDOR'), ('SEGURO', 'SEGURO'), ('EGRESO', 'EGRESO')], default='CREDITO', max_length=75, verbose_name='Tipo de Pago'),
        ),
    ]
