# Generated by Django 5.0.4 on 2024-11-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0005_payment_capital_generado_payment_interes_generado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='capital_generado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='interes_generado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
