# Generated by Django 5.0.4 on 2024-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0005_paymentplan_cambios'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='numero_referencia',
            field=models.CharField(blank=True, default='NAN', max_length=255, null=True, unique=True, verbose_name='Numero de Referencia'),
        ),
    ]
