# Generated by Django 5.0.4 on 2024-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0006_paymentplan_numero_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='descripcion_estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='factura',
            field=models.BooleanField(default=False),
        ),
    ]
