# Generated by Django 5.0.4 on 2025-02-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_email'),
        ('financings', '0006_alter_payment_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer'),
        ),
    ]
