# Generated by Django 5.0.4 on 2024-11-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0006_paymentplan_capital_generado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='interes_acumulado_generado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='mora_acumulado_generado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
