# Generated by Django 5.0.4 on 2024-11-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0007_paymentplan_interes_acumulado_generado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financings.paymentplan'),
        ),
    ]
