# Generated by Django 5.0.4 on 2025-03-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0007_alter_recibo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='registro_ficticio',
            field=models.BooleanField(default=False, verbose_name='Registro Ficticio'),
        ),
        migrations.AddField(
            model_name='payment',
            name='registro_ficticio',
            field=models.BooleanField(default=False, verbose_name='Registro Ficticio'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='estado_aportacion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
