# Generated by Django 4.2.16 on 2024-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0007_payment_descripcion_estado_recibo_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='numero_referencia',
            field=models.CharField(blank=True, default='NAN', max_length=255, null=True, verbose_name='Numero de Referencia'),
        ),
    ]
