# Generated by Django 4.2.16 on 2024-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0008_alter_paymentplan_numero_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tasa de Interes'),
        ),
    ]
