# Generated by Django 5.0.4 on 2025-04-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0008_banco_registro_ficticio_payment_registro_ficticio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='modifico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='numero_credito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='saldo_sin_modificar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
