# Generated by Django 5.0.4 on 2024-11-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0008_recibo_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='mora_generado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
