# Generated by Django 5.0.4 on 2025-04-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0009_credit_modifico_credit_numero_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='numero_credito',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='saldo_sin_modificar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
