# Generated by Django 5.0.4 on 2024-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0009_paymentplan_mora_generado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='mes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='No.Mes'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='principal_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Capital Pagado'),
        ),
    ]
