# Generated by Django 5.0.4 on 2024-11-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0010_alter_paymentplan_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='estado_aportacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='estado_fecha',
            field=models.BooleanField(default=False),
        ),
    ]
