# Generated by Django 5.0.4 on 2024-11-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0011_credit_estado_aportacion_credit_estado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='estado_fecha',
            field=models.BooleanField(default=True),
        ),
    ]
