# Generated by Django 5.0.4 on 2025-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0012_credit_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='estado_judicial',
            field=models.BooleanField(default=False, verbose_name='Estado Judicial'),
        ),
    ]
