# Generated by Django 5.0.4 on 2024-04-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0012_alter_credit_estado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_statement', to='financings.paymentplan'),
        ),
    ]
