# Generated by Django 5.0.4 on 2024-04-14 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0013_accountstatement_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='credit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financings.credit', verbose_name='Credito'),
        ),
    ]
