# Generated by Django 5.0.4 on 2024-12-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0014_alter_paymentplan_credit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='estado_fecha',
            new_name='estados_fechas',
        ),
    ]
