# Generated by Django 5.0.4 on 2025-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0014_credit_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='valoracion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Puntuacion del Credito'),
        ),
    ]
