# Generated by Django 5.0.4 on 2024-12-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0015_rename_estado_fecha_credit_estados_fechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='plazo_restante',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Plazo'),
        ),
    ]
