# Generated by Django 5.0.4 on 2025-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0015_alter_credit_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='correo_receptor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Correo Receptor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nit_receptor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='NIT RECEPTOR'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nombre_receptor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Receptor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Autorizacion'),
        ),
    ]
