# Generated by Django 5.0.4 on 2025-09-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0016_invoice_correo_receptor_invoice_nit_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='serie_autorizacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie de Autorizacion'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xml_certificado',
            field=models.TextField(blank=True, null=True, verbose_name='Serie de Autorizacion'),
        ),
    ]
