# Generated by Django 5.0.4 on 2025-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0017_invoice_serie_autorizacion_invoice_xml_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='identificador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='identificador'),
        ),
    ]
