# Generated by Django 5.0.4 on 2025-10-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0020_accountstatement_excedente'),
        ('subsidiaries', '0002_subsidiary_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
       
        migrations.AddField(
            model_name='invoice',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
    ]
