# Generated by Django 5.0.4 on 2025-10-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_creditcounselor_sucursal_customer_sucursal'),
        ('financings', '0021_banco_sucursal_credit_sucursal_invoice_sucursal_and_more'),
        ('subsidiaries', '0002_subsidiary_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='asesor_de_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.creditcounselor', verbose_name='Asesor de este Credito'),
        )
    ]
