# Generated by Django 5.0.4 on 2025-10-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0022_credit_asesor_de_credito_credit_sucursal'),
        ('subsidiaries', '0002_subsidiary_descripcion'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='paymentplan',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsidiaries.subsidiary'),
        ),
    ]
