# Generated by Django 5.0.4 on 2025-10-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0023_credit_sucursal_paymentplan_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='numero_identificacion_sucursal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Numero de Identificacion Sucursal por Cliente'),
        ),
    ]
