# Generated by Django 5.0.4 on 2025-11-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0024_credit_numero_identificacion_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cancelacion'),
        ),
    ]
