# Generated by Django 5.0.4 on 2025-11-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0025_credit_fecha_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='original_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
