# Generated by Django 5.0.4 on 2025-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0026_paymentplan_original_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='fecha_entrar_en_mora',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha en entrar en Mora'),
        ),
    ]
