# Generated by Django 5.0.4 on 2025-11-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0027_credit_fecha_entrar_en_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='es_visible',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Puede ser visible'),
        ),
    ]
