# Generated by Django 5.0.4 on 2025-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0028_accountstatement_es_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Tasa de Interes'),
        ),
    ]
