# Generated by Django 5.0.4 on 2026-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0030_accountstatement_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCreditoDemandado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
    ]
