# Generated by Django 5.0.4 on 2026-02-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0031_categoriacreditodemandado'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='categoria_credito_demandado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financings.categoriacreditodemandado', verbose_name='Categoria de Cliente Demandado'),
        ),
        migrations.AddField(
            model_name='credit',
            name='tipo_proceso',
            field=models.CharField(default='NORMAL', max_length=75, verbose_name='Tipo de Proceso de Pago'),
        ),
    ]
