# Generated by Django 5.0.4 on 2026-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0032_credit_categoria_credito_demandado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='tipo_proceso',
            field=models.CharField(blank=True, default='NORMAL', max_length=75, null=True, verbose_name='Tipo de Proceso de Pago'),
        ),
    ]
