# Generated by Django 5.0.4 on 2026-02-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0033_alter_credit_tipo_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='es_credito_migrado',
            field=models.BooleanField(default=False),
        ),
    ]
