# Generated by Django 5.0.4 on 2026-08-14 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0035_credit_fecha_finalizacion_gracia_credit_plazo_gracia_and_more'),
        ('subsidiaries', '0006_subsidiary_creation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('numero_referencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_descuento', models.DateTimeField(auto_now_add=True)),
                ('interes_por_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mora_por_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_capital_por_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_descuento', models.CharField(max_length=50)),
                ('motivo_descuento', models.TextField()),
                ('recalcular_cuota', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='financings.credit')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='financings.paymentplan')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='subsidiaries.subsidiary')),
                ('usuario_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-fecha_descuento'],
            },
        ),
    ]
