# Generated by Django 5.0.4 on 2026-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0036_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
