# Generated by Django 5.0.4 on 2026-08-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0037_descuento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='data_cuota',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
