# Generated by Django 5.0.4 on 2026-09-07 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0038_descuento_data_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglas', models.CharField(blank=True, choices=[('INTERES FIJO', 'INTERES FIJO'), ('CAPITAL FIJO', 'CAPITAL FIJO')], null=True, verbose_name='Reglas')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_credito', to='financings.credit')),
            ],
        ),
    ]
