# Generated by Django 5.0.4 on 2026-10-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0039_condicionescredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financings.payment', verbose_name='Pago'),
        ),
        migrations.AddConstraint(
            model_name='condicionescredito',
            constraint=models.UniqueConstraint(fields=('credit', 'reglas'), name='unique_regla_por_credito'),
        ),
    ]
