# Generated by Django 5.0.4 on 2026-10-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financings', '0040_alter_recibo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='forma_desembolso',
            field=models.CharField(choices=[('APLICACIÓN GASTOS', 'APLICACIÓN GASTOS'), ('APLICACIÓN DE AMPLIACIÓN DE CRÉDITO VIGENTE', 'APLICACIÓN DE AMPLIACIÓN DE CRÉDITO VIGENTE'), ('CANCELACIÓN DE CRÉDITO VIGENTE', 'CANCELACIÓN DE CRÉDITO VIGENTE'), ('REESTRUCTURACIÓN DE CRÉDITO VIGENTE', 'REESTRUCTURACIÓN DE CRÉDITO VIGENTE'), ('DESEMBOLSAR', 'DESEMBOLSAR')], max_length=75, verbose_name='Forma de Desembolso'),
        ),
    ]
