# Generated by Django 5.0.4 on 2025-01-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InvestmentPlan', '0002_initial'),
        ('addresses', '0002_initial'),
        ('customers', '0001_initial'),
        ('financings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/banco', verbose_name='Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Documeto de Banco',
                'verbose_name_plural': 'Documentos de Bancos',
            },
        ),
        migrations.CreateModel(
            name='DocumentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='addresses.address')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_documents', to='customers.customer')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_documents', to='documents.document')),
            ],
            options={
                'verbose_name': 'Documento de dirección',
                'verbose_name_plural': 'Documentos de Direcciones',
            },
        ),
        migrations.CreateModel(
            name='DocumentCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_documents', to='documents.document')),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
            },
        ),
        migrations.CreateModel(
            name='DocumentGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_documents', to='customers.customer')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_documents', to='documents.document')),
                ('garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_documents', to='financings.detailsguarantees')),
                ('investment_plan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='InvestmentPlan.investmentplan')),
            ],
            options={
                'verbose_name': 'Documento de Garantía',
                'verbose_name_plural': 'Documentos de Garantías',
            },
        ),
        migrations.CreateModel(
            name='DocumentOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_documents', to='customers.customer')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_documents', to='documents.document')),
            ],
            options={
                'verbose_name': 'Otro Documento',
                'verbose_name_plural': 'Otros Documentos',
            },
        ),
    ]
