# Generated by Django 5.0.4 on 2025-04-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentguarantee_customer_id'),
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddescription', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/sucursal/', verbose_name='Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_documents', to='subsidiaries.subsidiary')),
            ],
            options={
                'verbose_name': 'Documento de Sucursal',
                'verbose_name_plural': 'Documentos de Sucursales',
            },
        ),
    ]
