# Generated by Django 5.0.4 on 2025-11-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentbank_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Documento Sistema',
                'verbose_name_plural': 'Documentos Sistemas',
            },
        ),
    ]
