# Generated by Django 5.0.4 on 2025-11-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsistema',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/sistema/', verbose_name='Documento'),
        ),
    ]
