# Generated by Django 5.0.4 on 2025-12-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_customer_numero_identificacion_sucursal'),
        ('documents', '0006_alter_documentsistema_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='gestion/cobranza/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='customers.cobranza')),
            ],
        ),
    ]
