# Generated by Django 5.0.4 on 2025-12-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentocobranza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentocobranza',
            options={'verbose_name': 'Documento Cobranza', 'verbose_name_plural': 'Documentos Cobranzas'},
        ),
    ]
