# Generated by Django 5.0.4 on 2026-07-27 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentPlan', '0013_expedienteplannotario'),
        ('documents', '0009_documentsistema_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='gestion/expedientes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='InvestmentPlan.expedienteplannotario')),
            ],
            options={
                'verbose_name': 'Documento Expediente',
                'verbose_name_plural': 'Documentos Expedientes',
            },
        ),
    ]
