# Generated by Django 5.0.4 on 2026-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentexpediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentexpediente',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
