# Generated by Django 5.0.4 on 2026-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentexpediente_nombre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbank',
            name='nombre_del_banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Banco'),
        ),
    ]
